### PR TITLE
Assigned2 mark

### PR DESCRIPTION
**Pull request by Charlee1904**
Basic HTML frame.

### CODE REVIEW

**Review by ru14 — COMMENTED** [review]
looks good

**Review by ru14 — COMMENTED** [review]
fine

**Review by ru14 — COMMENTED** [review]
looking good

**Review by Charlee1904 — COMMENTED** [review]
Looks good.

**Comment by ru14** [comment]
check

**Review by AaronB22 — APPROVED** [review]

**Comment by AaronB22** [comment]
looks good

**Pull request merged**
